#spring:
#  datasource:
#    url: 'jdbc:h2:./devdb'
#    username: yaren
#  jpa:
#    hibernate:
#      ddl-auto: update
spring:
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none